spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/sensors_dev"
    password: postgres
    username: postgres
  jpa:
    generate-ddl: false
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
application:
  jwtCookieName: app-token
  jwtSecret: SensorAppBackSecretKeyForJWTTokenGeneration
  jwtExpirationMs: 86400000
